[observations]
obs_path = "my_domain/mizuroute_inputs/"
obs_file = "Athabasca_sedi_3_streamflow_observations.nc"
vname_obsflow = "q_obs"

[objective]
metric = "kge"
start_date = "2014-09-01"
end_date = "2024-12-31"

[mizuRoute]
namelist_path = "my_domain/mizuroute_inputs/"
namelist_file = "param.nml.default"
dt            = 3600
methods       = "3"
write_qbasin  = false
write_Qreach  = true

[hydrofabric]
hfabric_path      = "my_domain/mizuroute_inputs/"
hfabric_file      = "topology.nc"
dname_hru         = "hru"
dname_seg         = "seg"
varname_HRUid     = "hruId"
varname_segId     = "segId"
varname_hruSegId  = "hruToSegId"
varname_downSegId = "downSegId"
varname_area      = "area"
varname_slope     = "slope"
varname_length    = "length"
seg_outlet        = -9999
